services:
  - type: web
    name: ai-tts-service
    env: python
    plan: free
    # Simplified build command to reduce memory usage during build
    buildCommand: |
      pip install --no-cache-dir --upgrade pip==23.3.1 &&
      pip install --no-cache-dir torch==2.0.1 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cpu &&
      pip install --no-cache-dir -r requirements.txt
    # Optimized start command with memory limits
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1 --timeout-keep-alive 30 --limit-concurrency 5 --backlog 128"
    healthCheckPath: /health
    # Memory optimization environment variables
    envVars:
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
      # Aggressive memory management for PyTorch
      - key: PYTORCH_CUDA_ALLOC_CONF
        value: "max_split_size_mb:32"
      - key: OMP_NUM_THREADS
        value: "1"
      - key: MKL_NUM_THREADS
        value: "1"
      - key: NUMBA_CACHE_DIR
        value: "/tmp/numba_cache"
      # Python memory optimization
      - key: PYTHONMALLOC
        value: "malloc"
      - key: MALLOC_TRIM_THRESHOLD_
        value: "100000"
      # Disable unnecessary features
      - key: TOKENIZERS_PARALLELISM
        value: "false"