services:
  - type: web
    name: google-cloud-tts-service
    env: python
    plan: free
    # Simplified build command
    buildCommand: |
      pip install --no-cache-dir --upgrade pip setuptools wheel &&
      pip install --no-cache-dir -r requirements.txt
    # Simplified start command
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /health
    # Environment variables
    envVars:
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: "/etc/secrets/google-credentials.json"
    # Mount secrets
    secretFiles:
      - key: google-credentials.json
        path: /etc/secrets/google-credentials.json